### ISSUE TITLE
앱 출시 전 develop 브랜치 확인

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC2-Team8-Ssok#131]
## 📌 Issue
펄 문구 수정

## 📝 To-do
<!— 진행할 작업에 대해 적어주세요 —>
- [ ] What -> How로 변경하기
- [ ] 꼽다 -> 꽂다

**Comment by ChangJin-Lee** [comment]
마지막 업무 잘했어요 소다!
