### ISSUE TITLE
AddmemberView버그수정

### ISSUE THREAD

**Issue by sunhofficial** [DeveloperAcademy-POSTECH/MC2-Team8-Ssok#137]
## 📌 Issue
- AddmemberView에서 제대로된 이름을 치지않고 초성만치게되면 튕기는 이슈발생.
- UI작업.

## 📝 To-do
- [x] Alert문구 변경.
- [x] 사람이 없을때 다음버튼 비활성화
- [x] 초성작성시 앱 튕기는 문제발생

**Comment by ChangJin-Lee** [comment]
고생했습니다 선데이.
