### ISSUE TITLE
StrawView view-model 분리 작업

### ISSUE THREAD

**Issue by ChangJin-Lee** [DeveloperAcademy-POSTECH/MC2-Team8-Ssok#85]
TODO
- [x] StrawView ViewModel 분리
- [x] StrawView Refactoring

**Comment by ChangJin-Lee** [comment]
<img width="250" alt="스크린샷 2023-06-03 오전 2 24 33" src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap/assets/54494793/11d8a01b-0f91-420f-aac4-0b9e92ef6713">

다음과 같은 문제 발생

**Comment by ChangJin-Lee** [comment]
Conflict 문제였음.  
Ssock.xcodeproj 패키지보기 -> project.pbxproj  편집해서 해결

**Comment by ChangJin-Lee** [comment]
<img width="250" alt="스크린샷 2023-06-03 오전 2 24 33" src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap/assets/54494793/ff7f82a8-857b-4016-b20a-6120c1e15d65">

왼쪽 벽면에 공이 살짝 튀어나오는 문제가 발생.

**Comment by ChangJin-Lee** [comment]
<img width="200" alt="스크린샷 2023-06-03 오전 2 24 33" src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap/assets/54494793/93f9eb72-93b3-46a6-9adb-074955491104">


BottleViewModel leftBorder posoition을 바꿔 해결.

**Comment by sunhofficial** [comment]
이거 -120같은거 말고 비율로 해야 device크기가 달라져도 유지될거같아서 framewidth를 활용해서 나누는게 더 좋지않을까요?

**Comment by ChangJin-Lee** [comment]
f4ca873fdde97d4b0da2155dfde4f452223d23d5
BallView와 StrawView가 많이 가벼워진것 확인했습니다.

**Comment by pingse** [comment]
-120은 BottleViewModel에서 에셋 크기에 맞춘건데 device에 따라서는 StrawView에서 SpriteView을 조절하면 되는거라 상관없을 듯해요

**Comment by sunhofficial** [comment]
strawview에서 다음 뷰들로 각각넘어갈때 어떻게 짜야할까요? navigationstack하고 path계속 공부중인데 도저히 모르겠어요ㅠ 그 strawview에서 스위치 있는 쪽이요path.append해주어서 각각의 endingview로 넘어가게 해주려면 introview에서 destinatinostack설정할때 넘겨주어야 하는데 그때는 random값이 안뽑혀있어서 힘드네요 어떻게 할지. 시간 남는 사람들 같이 고민해보아요

**Comment by ChangJin-Lee** [comment]
시간 남는 사람 포크 뜨고 있던데요

**Comment by sunhofficial** [comment]
@minnnidev 누구에요?
